---
name: Dispatch Echo

on:
  workflow_dispatch:
    inputs:
      value:
        description: Value to be echoed
        type: string
        required: false
        default: Hello, World!

jobs:
  echo:
    name: Echo

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Sleep
        run: sleep 30

      - name: Echo
        run: echo ${{ inputs.value }}
